from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .......models.id403_error import Id403Error
    from .id_post_request_body import IdPostRequestBody
    from .id_post_response import IdPostResponse

class IdItemRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/templates/createFrom/{-id}/{id}
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new IdItemRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/templates/createFrom/{%2Did}/{id}", path_parameters)
    
    async def post(self,body: IdPostRequestBody, request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[IdPostResponse]:
        """
        Convenience alias for `POST /templates/createFrom/{id}` that accepts an explicit template `type` in the URL.Behaviour and permission checks are identical to the un-typed route. Useful when the client wants the URLto record which template type it expected, for routing or telemetry.
        param body: Body of a template.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[IdPostResponse]
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = self.to_post_request_information(
            body, request_configuration
        )
        from .......models.id403_error import Id403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": Id403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .id_post_response import IdPostResponse

        return await self.request_adapter.send_async(request_info, IdPostResponse, error_mapping)
    
    def to_post_request_information(self,body: IdPostRequestBody, request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Convenience alias for `POST /templates/createFrom/{id}` that accepts an explicit template `type` in the URL.Behaviour and permission checks are identical to the un-typed route. Useful when the client wants the URLto record which template type it expected, for routing or telemetry.
        param body: Body of a template.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = RequestInformation(Method.POST, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
        return request_info
    
    def with_url(self,raw_url: str) -> IdItemRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: IdItemRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return IdItemRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class IdItemRequestBuilderPostRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

