from enum import Enum

class MailPostRequestBody_supplementSheet(str, Enum):
    DEFAULT = "DEFAULT",
    NONE_ = "NONE",
    PAYTYPES = "PAYTYPES",
    SUPPORTS = "SUPPORTS",
    SUPPORTS_TICKETS = "SUPPORTS_TICKETS",
    EMPLOYEES = "EMPLOYEES",
    EMPLOYEES_INT = "EMPLOYEES_INT",
    PAYTYPES_SHORT = "PAYTYPES_SHORT",
    SUPPORTS_SHORT = "SUPPORTS_SHORT",
    SUPPORTS_TICKETS_SHORT = "SUPPORTS_TICKETS_SHORT",
    EMPLOYEES_SHORT = "EMPLOYEES_SHORT",
    EMPLOYEES_INT_SHORT = "EMPLOYEES_INT_SHORT",

