from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ....models.cars403_error import Cars403Error
    from .cars_get_response import CarsGetResponse
    from .item.cars_item_request_builder import CarsItemRequestBuilder

class CarsRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/cars
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new CarsRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/cars", path_parameters)
    
    def by_id(self,id: str) -> CarsItemRequestBuilder:
        """
        Gets an item from the tanss_api.rest.api.v1.cars.item collection
        param id: Id of the car.
        Returns: CarsItemRequestBuilder
        """
        if id is None:
            raise TypeError("id cannot be null.")
        from .item.cars_item_request_builder import CarsItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["id"] = id
        return CarsItemRequestBuilder(self.request_adapter, url_tpl_params)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[CarsGetResponse]:
        """
        Returns all cars of the company car pool. The entries are delivered in the reduced list view, so not every field of the single-car view is present. Standard admin access checks apply.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[CarsGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from ....models.cars403_error import Cars403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": Cars403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .cars_get_response import CarsGetResponse

        return await self.request_adapter.send_async(request_info, CarsGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns all cars of the company car pool. The entries are delivered in the reduced list view, so not every field of the single-car view is present. Standard admin access checks apply.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> CarsRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: CarsRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return CarsRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class CarsRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

