from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ......models.cost_center403_error import CostCenter403Error
    from .cost_center_get_response import CostCenterGetResponse

class CostCenterItemRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/companies/costCenter/{id}
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new CostCenterItemRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/companies/costCenter/{id}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[CostCenterGetResponse]:
        """
        Returns the cost-center configuration for a company (whether cost centers are used, the list of defined cost centers, and assignments to PCs / peripherals / employees). The caller must have access to the company. If the company is a branch without its own configuration, the lookup falls back to the headquarter's cost-center setup.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[CostCenterGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from ......models.cost_center403_error import CostCenter403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": CostCenter403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .cost_center_get_response import CostCenterGetResponse

        return await self.request_adapter.send_async(request_info, CostCenterGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns the cost-center configuration for a company (whether cost centers are used, the list of defined cost centers, and assignments to PCs / peripherals / employees). The caller must have access to the company. If the company is a branch without its own configuration, the lookup falls back to the headquarter's cost-center setup.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> CostCenterItemRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: CostCenterItemRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return CostCenterItemRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class CostCenterItemRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

