from enum import Enum

class SupportsPostRequestBody_status(str, Enum):
    NEW = "NEW",
    APPROVED = "APPROVED",
    DECLINED = "DECLINED",
    PAYOUT_REQUESTED = "PAYOUT_REQUESTED",
    PAYOUT_APPROVED = "PAYOUT_APPROVED",
    PAYOUT_DECLINED = "PAYOUT_DECLINED",
    VACATION_REQUESTED = "VACATION_REQUESTED",
    VACATION_APPROVED = "VACATION_APPROVED",
    VACATION_DECLINED = "VACATION_DECLINED",

