from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.reimport_solr403_error import ReimportSolr403Error
    from .reimport_solr_get_response import ReimportSolrGetResponse

class ReimportSolrRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/util/reimportSolr
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ReimportSolrRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/util/reimportSolr", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[ReimportSolrGetResponse]:
        """
        Triggers a full reimport of every search collection into Solr by calling the loader service's `init`. This is a slow operation; the controller answers with 201 once the import has been scheduled. Requires a technician/freelancer with both `MANAGE_PERMISSIONS` and `ONLINE_SYSTEM_CONFIGURATION`.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[ReimportSolrGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .....models.reimport_solr403_error import ReimportSolr403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": ReimportSolr403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .reimport_solr_get_response import ReimportSolrGetResponse

        return await self.request_adapter.send_async(request_info, ReimportSolrGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Triggers a full reimport of every search collection into Solr by calling the loader service's `init`. This is a slow operation; the controller answers with 201 once the import has been scheduled. Requires a technician/freelancer with both `MANAGE_PERMISSIONS` and `ONLINE_SYSTEM_CONFIGURATION`.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> ReimportSolrRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ReimportSolrRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ReimportSolrRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class ReimportSolrRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

