from enum import Enum

class TemplatesPutRequestBody_type(str, Enum):
    CONTRACT = "CONTRACT",
    TICKET = "TICKET",
    PROJECT = "PROJECT",
    CHECKLIST = "CHECKLIST",
    PERSONALCOMPUTER = "PERSONALCOMPUTER",
    PERIPHERY = "PERIPHERY",
    COMPONENT = "COMPONENT",
    SOFTWARELICENSE = "SOFTWARELICENSE",
    PLANNING = "PLANNING",
    STATISTIC_ALL_SERVICES_BY_DAY = "STATISTIC_ALL_SERVICES_BY_DAY",
    SUPPORTCONFIGURATION = "SUPPORTCONFIGURATION",
    TICKETCONFIGURATION = "TICKETCONFIGURATION",
    SUPPORT = "SUPPORT",
    SUPPORT_PERSONAL = "SUPPORT_PERSONAL",
    STATISTICS_APPROVAL_OF_SUPPORTS = "STATISTICS_APPROVAL_OF_SUPPORTS",

