from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.global_panels403_error import GlobalPanels403Error
    from .global_panels_get_response import GlobalPanelsGetResponse

class GlobalPanelsRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/ticketBoard/globalPanels
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new GlobalPanelsRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/ticketBoard/globalPanels", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[GlobalPanelsGetResponse]:
        """
        Returns every ticket board panel with visibility `EVERYBODY` — the panels that are shared across the whole tenant, regardless of who created them or which departments/employees they are scoped to. The caller still needs ticket board access (technician/freelancer with `TICKET_BOARD_ACCESS`, dashboard viewer, or board administrator).
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[GlobalPanelsGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .....models.global_panels403_error import GlobalPanels403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": GlobalPanels403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .global_panels_get_response import GlobalPanelsGetResponse

        return await self.request_adapter.send_async(request_info, GlobalPanelsGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns every ticket board panel with visibility `EVERYBODY` — the panels that are shared across the whole tenant, regardless of who created them or which departments/employees they are scoped to. The caller still needs ticket board access (technician/freelancer with `TICKET_BOARD_ACCESS`, dashboard viewer, or board administrator).
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> GlobalPanelsRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: GlobalPanelsRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return GlobalPanelsRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class GlobalPanelsRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

