from enum import Enum

class TnsChatLogType(str, Enum):
    CLOSED = "CLOSED",
    REOPENED = "REOPENED",
    ADDED_EMPLOYEE = "ADDED_EMPLOYEE",
    ADDED_DEPARTMENT = "ADDED_DEPARTMENT",
    REMOVED_EMPLOYEE = "REMOVED_EMPLOYEE",
    REMOVED_DEPARTMENT = "REMOVED_DEPARTMENT",
    REQUESTED_CLOSING = "REQUESTED_CLOSING",
    DECLINED_CLOSING = "DECLINED_CLOSING",

