from enum import Enum

class TnsCustomerPortalWidgetActionType(str, Enum):
    CREATE_TICKET = "CREATE_TICKET",
    CREATE_SUPPORT = "CREATE_SUPPORT",
    TICKET_PRIORITY = "TICKET_PRIORITY",
    TICKET_DUE_DATE = "TICKET_DUE_DATE",
    TICKET_DEADLINE_DATE = "TICKET_DEADLINE_DATE",
    ADD_CHECKLIST = "ADD_CHECKLIST",
    TAG = "TAG",
    ADD_COMMENT = "ADD_COMMENT",
    SEND_MAIL = "SEND_MAIL",

