from enum import Enum

class TnsLLMModel(str, Enum):
    GPT_4O_MINI = "GPT_4O_MINI",
    GPT_4O = "GPT_4O",
    GEMINI_2_0_FLASH = "GEMINI_2_0_FLASH",
    GEMINI_1_5_FLASH = "GEMINI_1_5_FLASH",
    TANSS_AI_GEMMA_3_4_B = "TANSS_AI_GEMMA_3_4_B",
    TANSS_AI_MISTRAL_SMALL_3_2_24_B = "TANSS_AI_MISTRAL_SMALL_3_2_24_B",
    TANSS_AI_GEMMA_3_27_B = "TANSS_AI_GEMMA_3_27_B",
    TANSS_AI_MISTRAL_SMALL_3_1_24_B = "TANSS_AI_MISTRAL_SMALL_3_1_24_B",

