from enum import Enum

class TnsTicketNotificationReason(str, Enum):
    STATUS_CHANGED = "STATUS_CHANGED",
    ASSIGNED_TO_ANOTHER_TECHNICIAN = "ASSIGNED_TO_ANOTHER_TECHNICIAN",
    NEW_COMMENT = "NEW_COMMENT",
    NEW_SUPPORT = "NEW_SUPPORT",
    TICKET_CREATED = "TICKET_CREATED",
    TICKET_REMINDER = "TICKET_REMINDER",
    EMAIL_RECEIVED = "EMAIL_RECEIVED",
    TICKET_NOT_MORE_ASSIGNED_TO_SELF = "TICKET_NOT_MORE_ASSIGNED_TO_SELF",
    NEW_SERVICE_CAP = "NEW_SERVICE_CAP",
    TICKET_CLOSED = "TICKET_CLOSED",
    NEW_DUE_DATE = "NEW_DUE_DATE",
    NEW_DEADLINE = "NEW_DEADLINE",
    CHANGED_TAGS = "CHANGED_TAGS",

