from enum import Enum

class TnsCallbackState(str, Enum):
    UNSEEN = "UNSEEN",
    NEW = "NEW",
    NOBODY_ANSWERED = "NOBODY_ANSWERED",
    BUSY = "BUSY",
    NOT_PRESENT = "NOT_PRESENT",
    NEW_CALLBACK_REENTERED = "NEW_CALLBACK_REENTERED",
    COMPLETED = "COMPLETED",
    EXPECTED_CALLBACK = "EXPECTED_CALLBACK",
    EXPECTED_CALLBACK_COMPLETED = "EXPECTED_CALLBACK_COMPLETED",

