from enum import Enum

class TnsPlanningType(str, Enum):
    SUPPORT = "SUPPORT",
    APPOINTMENT_PROPOSAL = "APPOINTMENT_PROPOSAL",
    APPOINTMENT_FIX = "APPOINTMENT_FIX",
    VACATION = "VACATION",
    ILLNESS = "ILLNESS",
    ABSENCE = "ABSENCE",
    STAND_BY = "STAND_BY",
    APPOINTMENT_PRIVATE = "APPOINTMENT_PRIVATE",
    OVERTIME = "OVERTIME",
    CUSTOM = "CUSTOM",

