from enum import Enum

class TnsChecklistItemType(str, Enum):
    TEXT_FIELD = "TEXT_FIELD",
    REQUIRED_FIELD = "REQUIRED_FIELD",
    OPTIONAL_FIELD = "OPTIONAL_FIELD",
    INCLUDED_CHECKLIST = "INCLUDED_CHECKLIST",
    REQUIRED_TEXT_FIELD = "REQUIRED_TEXT_FIELD",
    OPTIONAL_TEXT_FIELD = "OPTIONAL_TEXT_FIELD",
    REQUIRED_MULTISELECT = "REQUIRED_MULTISELECT",
    OPTIONAL_MULTISELECT = "OPTIONAL_MULTISELECT",
    EVENT_CONTAINER = "EVENT_CONTAINER",
    APPROVAL_PROCESS = "APPROVAL_PROCESS",

