from enum import Enum

class TnsMailRobotAction_type(str, Enum):
    CLOSE_TICKET = "CLOSE_TICKET",
    CREATE_TICKET = "CREATE_TICKET",
    CREATE_SUPPORT = "CREATE_SUPPORT",
    CREATE_DOCUMENT = "CREATE_DOCUMENT",
    PROCESS_TASK = "PROCESS_TASK",
    CREATE_COMPANY_DATA = "CREATE_COMPANY_DATA",
    GET_VAR = "GET_VAR",
    SEND_EMAIL = "SEND_EMAIL",
    CREATE_CALLBACK = "CREATE_CALLBACK",
    DETERMINE_DATA = "DETERMINE_DATA",
    VEEAM_BACKUP = "VEEAM_BACKUP",
    ASSIGN_TICKET_ROLE = "ASSIGN_TICKET_ROLE",

