from enum import Enum

class TnsTextModuleType(str, Enum):
    TICKET = "TICKET",
    TICKET_COMMENT = "TICKET_COMMENT",
    SUPPORT = "SUPPORT",
    CONTRACT_COMMENT = "CONTRACT_COMMENT",
    CONTRACT_ADDITIONAL = "CONTRACT_ADDITIONAL",
    CONTRACT_SPECIAL = "CONTRACT_SPECIAL",
    E_MAIL_COMMUNICATION = "E_MAIL_COMMUNICATION",
    RESUBMISSION_TEXT = "RESUBMISSION_TEXT",
    DOCUMENT = "DOCUMENT",
    NOT_CHARGED_REASON = "NOT_CHARGED_REASON",
    OFFER_TEXT = "OFFER_TEXT",
    OFFER_STATUS = "OFFER_STATUS",

