from enum import Enum

class TnsWorkflowContractState(str, Enum):
    CREATED = "CREATED",
    REQUEST_SENT = "REQUEST_SENT",
    REQUEST_SEND_ERROR = "REQUEST_SEND_ERROR",
    LANDING_PAGE_1_OPENED = "LANDING_PAGE_1_OPENED",
    CONTRACT_REQUESTED = "CONTRACT_REQUESTED",
    LANDING_PAGE_2_OPENED = "LANDING_PAGE_2_OPENED",
    CONTRACT_DECLINED = "CONTRACT_DECLINED",
    CONTRACT_CANCELLED = "CONTRACT_CANCELLED",
    CONTRACT_AVAILABLE = "CONTRACT_AVAILABLE",
    CONTRACT_UPLOADED_MANUALLY = "CONTRACT_UPLOADED_MANUALLY",
    STATE_SET_MANUALLY = "STATE_SET_MANUALLY",

