from enum import Enum

class TnsTicketMenuItem(str, Enum):
    ADD_FILES = "ADD_FILES",
    ASSIGN_NEW_SUB_TICKET = "ASSIGN_NEW_SUB_TICKET",
    ASSIGN_TO_PROJECT = "ASSIGN_TO_PROJECT",
    CREATE_NEW_CLOUD_UPLOAD = "CREATE_NEW_CLOUD_UPLOAD",
    CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT",
    CREATE_NEW_EMAIL = "CREATE_NEW_EMAIL",
    CREATE_NEW_SUB_TICKET = "CREATE_NEW_SUB_TICKET",
    CREATE_NEW_SUPPORT = "CREATE_NEW_SUPPORT",
    NEW_PROJECT_PHASE = "NEW_PROJECT_PHASE",
    PROJECT_PLANNING = "PROJECT_PLANNING",

