from enum import Enum

class TnsOpenTicketsFilter(str, Enum):
    SUPPORTS_FROM_ALL_TICKETS = "SUPPORTS_FROM_ALL_TICKETS",
    SUPPORTS_FROM_OPEN_TICKETS = "SUPPORTS_FROM_OPEN_TICKETS",
    SUPPORTS_FROM_CLOSED_TICKETS = "SUPPORTS_FROM_CLOSED_TICKETS",
    ALL_SUPPORTS_BUT_OPEN_TICKETS = "ALL_SUPPORTS_BUT_OPEN_TICKETS",

