from enum import Enum

class TnsTanssEventTriggerType(str, Enum):
    TICKET_STATUS_CHANGED = "TICKET_STATUS_CHANGED",
    TICKET_ASSIGNED_TO_ANOTHER_TECHNICIAN = "TICKET_ASSIGNED_TO_ANOTHER_TECHNICIAN",
    TICKET_NEW_COMMENT = "TICKET_NEW_COMMENT",
    TICKET_NEW_SUPPORT = "TICKET_NEW_SUPPORT",
    TICKET_CREATED = "TICKET_CREATED",
    TICKET_REMINDER = "TICKET_REMINDER",
    TICKET_EMAIL_RECEIVED = "TICKET_EMAIL_RECEIVED",
    TICKET_NOT_MORE_ASSIGNED_TO_SELF = "TICKET_NOT_MORE_ASSIGNED_TO_SELF",
    TICKET_NEW_SERVICE_CAP = "TICKET_NEW_SERVICE_CAP",
    TICKET_CLOSED = "TICKET_CLOSED",
    TICKET_NEW_DUE_DATE = "TICKET_NEW_DUE_DATE",
    TICKET_NEW_DEADLINE = "TICKET_NEW_DEADLINE",
    TICKET_RESUBMISSION_HIT = "TICKET_RESUBMISSION_HIT",
    TICKET_TAGS_CHANGED = "TICKET_TAGS_CHANGED",

