from enum import Enum

class TnsPortalProfileType(str, Enum):
    NONE_ = "NONE",
    DEFAULT = "DEFAULT",
    DEFAULT_INTERNAL = "DEFAULT_INTERNAL",
    DEFAULT_EXTRNAL = "DEFAULT_EXTRNAL",
    CONVERTED_PORTAL = "CONVERTED_PORTAL",
    CONVERTED_CUSTOMER_PORTAL = "CONVERTED_CUSTOMER_PORTAL",
    PLANNING = "PLANNING",
    TICKETBOARD = "TICKETBOARD",

