from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ......models.screenshots403_error import Screenshots403Error
    from .item.with_image_item_request_builder import WithImageItemRequestBuilder
    from .screenshots_get_response import ScreenshotsGetResponse

class ScreenshotsRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/tickets/{-id}/screenshots
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ScreenshotsRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/tickets/{%2Did}/screenshots", path_parameters)
    
    def by_image_id(self,image_id: int) -> WithImageItemRequestBuilder:
        """
        Gets an item from the tanss_api.rest.api.v1.tickets.item.screenshots.item collection
        param image_id: id of the image
        Returns: WithImageItemRequestBuilder
        """
        if image_id is None:
            raise TypeError("image_id cannot be null.")
        from .item.with_image_item_request_builder import WithImageItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["imageId"] = image_id
        return WithImageItemRequestBuilder(self.request_adapter, url_tpl_params)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[ScreenshotsGetResponse]:
        """
        Gets all the images attached to a ticket
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[ScreenshotsGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from ......models.screenshots403_error import Screenshots403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": Screenshots403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .screenshots_get_response import ScreenshotsGetResponse

        return await self.request_adapter.send_async(request_info, ScreenshotsGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Gets all the images attached to a ticket
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> ScreenshotsRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ScreenshotsRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ScreenshotsRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class ScreenshotsRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

