from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ......models.with_configuration403_error import WithConfiguration403Error

class WithConfigurationItemRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/ical/fetch/{configurationId}
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new WithConfigurationItemRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/ical/fetch/{configurationId}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[bytes]:
        """
        Returns a `text/calendar` (iCalendar) feed for the given configuration so external calendar clients (Outlook, Google Calendar, Apple Calendar, Thunderbird) can subscribe to a technician's planned supports and appointments. Unlike the rest of the API this route uses HTTP Basic Auth (calendar clients cannot carry JWTs), and the configuration controls which employees and planning types are exported. If the configuration was deleted or has no body, a sensible default scoped to the logged-in user is returned.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: bytes
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from ......models.with_configuration403_error import WithConfiguration403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": WithConfiguration403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        return await self.request_adapter.send_primitive_async(request_info, "bytes", error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns a `text/calendar` (iCalendar) feed for the given configuration so external calendar clients (Outlook, Google Calendar, Apple Calendar, Thunderbird) can subscribe to a technician's planned supports and appointments. Unlike the rest of the API this route uses HTTP Basic Auth (calendar clients cannot carry JWTs), and the configuration controls which employees and planning types are exported. If the configuration was deleted or has no body, a sensible default scoped to the logged-in user is returned.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "text/calendar, application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> WithConfigurationItemRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: WithConfigurationItemRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return WithConfigurationItemRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class WithConfigurationItemRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

