from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.with_role403_error import WithRole403Error
    from .with_role_get_response import WithRoleGetResponse

class WithRoleRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/tickets/withRole
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new WithRoleRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/tickets/withRole", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[WithRoleGetResponse]:
        """
        Returns tickets where the logged-in employee holds an explicit role — maintechnician, co-technician, observer, etc. — rather than only those assignedvia the default `assigneeId`.Useful for surfacing involvement that does not show up in`GET /api/v1/tickets/own`, such as tickets the technician is supporting onor watching without being the primary owner.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[WithRoleGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .....models.with_role403_error import WithRole403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": WithRole403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .with_role_get_response import WithRoleGetResponse

        return await self.request_adapter.send_async(request_info, WithRoleGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns tickets where the logged-in employee holds an explicit role — maintechnician, co-technician, observer, etc. — rather than only those assignedvia the default `assigneeId`.Useful for surfacing involvement that does not show up in`GET /api/v1/tickets/own`, such as tickets the technician is supporting onor watching without being the primary owner.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> WithRoleRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: WithRoleRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return WithRoleRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class WithRoleRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

