from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.types403_error import Types403Error
    from .item.with_type_name_item_request_builder import WithTypeNameItemRequestBuilder
    from .types_get_response import TypesGetResponse

class TypesRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/tickets/types
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new TypesRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/tickets/types", path_parameters)
    
    def by_type_name(self,type_name: str) -> WithTypeNameItemRequestBuilder:
        """
        Gets an item from the tanss_api.rest.api.v1.tickets.types.item collection
        param type_name: Name of the new ticket type to create.
        Returns: WithTypeNameItemRequestBuilder
        """
        if type_name is None:
            raise TypeError("type_name cannot be null.")
        from .item.with_type_name_item_request_builder import WithTypeNameItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["typeName"] = type_name
        return WithTypeNameItemRequestBuilder(self.request_adapter, url_tpl_params)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[TypesGetResponse]:
        """
        Returns only the active ticket types — used to populate the type drop-downwhen creating or editing a ticket. For the full admin list (includinginactive), use `GET /api/v1/admin/ticketTypes`.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[TypesGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .....models.types403_error import Types403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": Types403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .types_get_response import TypesGetResponse

        return await self.request_adapter.send_async(request_info, TypesGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns only the active ticket types — used to populate the type drop-downwhen creating or editing a ticket. For the full admin list (includinginactive), use `GET /api/v1/admin/ticketTypes`.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> TypesRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: TypesRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return TypesRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class TypesRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

