from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.readable_text403_error import ReadableText403Error
    from .readable_text_post_request_body import ReadableTextPostRequestBody
    from .readable_text_post_response import ReadableTextPostResponse

class ReadableTextRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/recurrence/readableText
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ReadableTextRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/recurrence/readableText", path_parameters)
    
    async def post(self,body: ReadableTextPostRequestBody, request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[ReadableTextPostResponse]:
        """
        Returns a human-readable description of a recurrence rule (e.g. "every Monday until 2026-01-01") for display in the UI. The rule itself is not persisted; this is a formatting helper.
        param body: The request body
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[ReadableTextPostResponse]
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = self.to_post_request_information(
            body, request_configuration
        )
        from .....models.readable_text403_error import ReadableText403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": ReadableText403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .readable_text_post_response import ReadableTextPostResponse

        return await self.request_adapter.send_async(request_info, ReadableTextPostResponse, error_mapping)
    
    def to_post_request_information(self,body: ReadableTextPostRequestBody, request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns a human-readable description of a recurrence rule (e.g. "every Monday until 2026-01-01") for display in the UI. The rule itself is not persisted; this is a formatting helper.
        param body: The request body
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = RequestInformation(Method.POST, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
        return request_info
    
    def with_url(self,raw_url: str) -> ReadableTextRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ReadableTextRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ReadableTextRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class ReadableTextRequestBuilderPostRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

