from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .......models.show403_error import Show403Error
    from .show_get_response import ShowGetResponse

class ShowRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/companies/{company-id}/types/show
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new ShowRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/companies/{company%2Did}/types/show", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[ShowGetResponse]:
        """
        Returns the list of records ordered by their `rank` — i.e. the catalog of "important company info" fields an admin has set up (label, type, ordering). This is used by the admin UI to render the configuration of the important-info section. Requires the `EDIT_IMPORTANT_COMPANY_INFO` permission.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[ShowGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .......models.show403_error import Show403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": Show403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .show_get_response import ShowGetResponse

        return await self.request_adapter.send_async(request_info, ShowGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns the list of records ordered by their `rank` — i.e. the catalog of "important company info" fields an admin has set up (label, type, ordering). This is used by the admin UI to render the configuration of the important-info section. Requires the `EDIT_IMPORTANT_COMPANY_INFO` permission.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> ShowRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: ShowRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return ShowRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class ShowRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

