from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.absent_technicians403_error import AbsentTechnicians403Error
    from .absent_technicians_get_response import AbsentTechniciansGetResponse

class AbsentTechniciansRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/tickets/absentTechnicians
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new AbsentTechniciansRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/tickets/absentTechnicians", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[AbsentTechniciansGetResponse]:
        """
        Returns open tickets currently assigned to technicians who are marked as absent(vacation, sick leave, etc.). Used by dispatchers to identify work that needs tobe re-assigned while the owner is away. Requires the caller to be a technicianor freelancer.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[AbsentTechniciansGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .....models.absent_technicians403_error import AbsentTechnicians403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": AbsentTechnicians403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .absent_technicians_get_response import AbsentTechniciansGetResponse

        return await self.request_adapter.send_async(request_info, AbsentTechniciansGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns open tickets currently assigned to technicians who are marked as absent(vacation, sick leave, etc.). Used by dispatchers to identify work that needs tobe re-assigned while the owner is away. Requires the caller to be a technicianor freelancer.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> AbsentTechniciansRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: AbsentTechniciansRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return AbsentTechniciansRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class AbsentTechniciansRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

