from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .......models.registers403_error import Registers403Error
    from .registers_get_response import RegistersGetResponse

class RegistersRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /api/v1/ticketBoard/panel/{-id}/registers
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new RegistersRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/api/v1/ticketBoard/panel/{%2Did}/registers", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[RegistersGetResponse]:
        """
        Returns the panel's registers — the column groupings shown inside the panel (e.g. one register per ticket status, type, tag or project phase, depending on `registerType`) together with the tickets currently assigned to each register, already filtered by the calling employee's panel filter. The optional `registerType` query parameter can override the panel's configured register type.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[RegistersGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        from .......models.registers403_error import Registers403Error

        error_mapping: dict[str, type[ParsableFactory]] = {
            "403": Registers403Error,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .registers_get_response import RegistersGetResponse

        return await self.request_adapter.send_async(request_info, RegistersGetResponse, error_mapping)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        Returns the panel's registers — the column groupings shown inside the panel (e.g. one register per ticket status, type, tag or project phase, depending on `registerType`) together with the tickets currently assigned to each register, already filtered by the calling employee's panel filter. The optional `registerType` query parameter can override the panel's configured register type.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> RegistersRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: RegistersRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return RegistersRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class RegistersRequestBuilderGetRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

